name: remote ssh command
on: 
  push:
    branches:
      - master
  pull_request:
        types: [synchronized]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd prj
          rm -rf api2
          git clone https://github.com/ALTA-BE16-iqbal/api2.git
          ls -al
          cd api2
          go run main.go
